version: "3.4"
   
services:
  db:
   build: 
     context: db
     dockerfile: Dockerfile
   container_name: db
   volumes:
      - ./data/db:/var/lib/postgresql/data
   environment:
    - POSTGRES_USER=gisuser
    - POSTGRES_PASS=run/secrets/db_password
    - POSTGRES_DBNAME=gis
   ports:
   - "5432:5432"
   secrets:
      - db_password
      
  web:
    build: 
     context: backend
     dockerfile: Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_HOST=db
      - POSTGRES_USER=gisuser
      - POSTGRES_PASS=run/secrets/db_password
      - POSTGRES_DBNAME=gis
      - AWS_SECRET_ACCES_KEY=run/secrets/db_password
      - AWS_ACCES_KEY_ID=run/secrets/db_password
    volumes:
      - ./backend/:/src/app
    ports:
      - "8000:8000"
    depends_on:
      - fixture
    secrets:
      - db_password

  migrate:
    build: 
     context: backend
    container_name: migrate
    command: python manage.py migrate
    volumes:
      - ./backend/:/src/app
    environment:
      - DATABASE_HOST=db
      - POSTGRES_USER=gisuser
      - POSTGRES_PASS=run/secrets/db_password
      - POSTGRES_DBNAME=gis
    depends_on:
      - db
    secrets:
      - db_password
  
  fixture:
    build: 
     context: backend
    container_name: fixture
    command: python manage.py loaddata fixtures/*.json
    volumes:
      - ./backend/:/src/app
    environment:
      - DATABASE_HOST=db
      - POSTGRES_USER=gisuser
      - POSTGRES_PASS=/run/secrets/db_password
      - POSTGRES_DBNAME=gis
    depends_on:
      - migrate
    secrets:
      - db_password

secrets:
  db_password:
    file: db_password.txt
